export function createStyles(theme) {
  const isDark = theme === 'dark'

  const colors = {
    pageBg: isDark
      ? 'radial-gradient(circle at top left, #1e293b 0, #020617 42%, #000 100%)'
      : 'radial-gradient(circle at top left, #dbeafe 0, #f8fafc 38%, #e5e7eb 100%)',
    panelBg: isDark ? 'rgba(15, 23, 42, 0.82)' : 'rgba(255,255,255,0.96)',
    panelStrong: isDark ? 'rgba(15, 23, 42, 0.96)' : 'rgba(255,255,255,0.98)',
    text: isDark ? '#e5e7eb' : '#111827',
    muted: isDark ? '#9ca3af' : '#4b5563',
    subtle: isDark ? '#64748b' : '#6b7280',
    border: isDark ? 'rgba(51, 65, 85, 0.95)' : 'rgba(209,213,219,1)',
    accent: isDark ? '#60a5fa' : '#2563eb',
    accentSoft: isDark ? 'rgba(37,99,235,0.26)' : 'rgba(37,99,235,0.10)',
    accentBorder: isDark ? 'rgba(96,165,250,0.9)' : 'rgba(37,99,235,0.75)',
    okBg: isDark ? 'rgba(6, 95, 70, 0.72)' : 'rgba(16,185,129,0.12)',
    okBorder: isDark ? 'rgba(16, 185, 129, 0.72)' : 'rgba(16,185,129,0.9)',
  }

  return {
    app: {
      minHeight: '100vh',
      fontFamily:
        'Inter, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
      background: colors.pageBg,
      color: colors.text,
      transition: 'background 0.35s ease, color 0.35s ease',
    },
    layout: {
      maxWidth: '1120px',
      margin: '0 auto',
      padding: '2.25rem 1.25rem 3.5rem',
      boxSizing: 'border-box',
    },
    topBar: {
      display: 'flex',
      justifyContent: 'space-between',
      alignItems: 'center',
      gap: '1rem',
      marginBottom: '1.35rem',
      flexWrap: 'wrap',
    },
    topBarGroup: {
      display: 'flex',
      alignItems: 'center',
      gap: '0.5rem',
      flexWrap: 'wrap',
      fontSize: '0.8rem',
    },
    toggleLabel: {
      fontSize: '0.72rem',
      textTransform: 'uppercase',
      letterSpacing: '0.12em',
      color: colors.subtle,
    },
    toggleButton: {
      borderRadius: '999px',
      border: `1px solid ${colors.border}`,
      padding: '0.35rem 0.78rem',
      fontSize: '0.8rem',
      background: isDark ? 'rgba(15,23,42,0.88)' : 'rgba(255,255,255,0.9)',
      color: colors.text,
      cursor: 'pointer',
      display: 'inline-flex',
      alignItems: 'center',
      gap: '0.3rem',
      transition:
        'background 0.2s ease, color 0.2s ease, border-color 0.2s ease, transform 0.12s ease',
    },
    toggleButtonActive: {
      background: colors.accentSoft,
      borderColor: colors.accentBorder,
      color: isDark ? '#bfdbfe' : '#1d4ed8',
    },
    pdfButton: {
      borderRadius: '999px',
      border: `1px solid ${colors.accentBorder}`,
      padding: '0.4rem 0.9rem',
      fontSize: '0.8rem',
      background: colors.accentSoft,
      color: isDark ? '#bfdbfe' : '#1d4ed8',
      cursor: 'pointer',
      display: 'inline-flex',
      alignItems: 'center',
      gap: '0.35rem',
      textDecoration: 'none',
    },
    header: {
      display: 'grid',
      gridTemplateColumns: 'minmax(0, 1fr) minmax(260px, 340px)',
      gap: '1.4rem',
      alignItems: 'stretch',
      marginBottom: '1.8rem',
    },
    heroContent: {
      background: colors.panelBg,
      border: `1px solid ${colors.border}`,
      borderRadius: '1.25rem',
      padding: '1.55rem',
      boxShadow: isDark
        ? '0 22px 48px rgba(0,0,0,0.32)'
        : '0 22px 48px rgba(148,163,184,0.32)',
    },
    chip: {
      display: 'inline-block',
      padding: '0.28rem 0.72rem',
      borderRadius: '999px',
      border: `1px solid ${colors.border}`,
      fontSize: '0.7rem',
      textTransform: 'uppercase',
      letterSpacing: '0.08em',
      color: colors.text,
      backgroundColor: isDark ? 'rgba(15,23,42,0.86)' : 'rgba(255,255,255,0.88)',
    },
    name: {
      fontSize: 'clamp(2.2rem, 5vw, 4rem)',
      fontWeight: 800,
      letterSpacing: '-0.055em',
      lineHeight: 1,
      margin: '0.8rem 0 0',
    },
    subtitle: {
      fontSize: 'clamp(1rem, 2vw, 1.25rem)',
      color: colors.accent,
      marginTop: '0.7rem',
      maxWidth: '760px',
      fontWeight: 650,
      lineHeight: 1.45,
    },
    heroSummary: {
      fontSize: '0.98rem',
      color: colors.muted,
      lineHeight: 1.7,
      maxWidth: '780px',
      marginTop: '0.9rem',
    },
    heroActions: {
      display: 'flex',
      flexWrap: 'wrap',
      gap: '0.65rem',
      marginTop: '1.1rem',
    },
    primaryButton: {
      borderRadius: '999px',
      border: `1px solid ${colors.accentBorder}`,
      padding: '0.55rem 1rem',
      background: isDark ? 'rgba(37,99,235,0.45)' : 'rgba(37,99,235,0.95)',
      color: '#ffffff',
      textDecoration: 'none',
      fontSize: '0.88rem',
      fontWeight: 650,
      display: 'inline-flex',
      alignItems: 'center',
    },
    secondaryButton: {
      borderRadius: '999px',
      border: `1px solid ${colors.border}`,
      padding: '0.55rem 1rem',
      background: isDark ? 'rgba(15,23,42,0.7)' : 'rgba(255,255,255,0.9)',
      color: colors.text,
      textDecoration: 'none',
      fontSize: '0.88rem',
      fontWeight: 600,
      display: 'inline-flex',
      alignItems: 'center',
    },
    contactCard: {
      background: colors.panelStrong,
      borderRadius: '1.25rem',
      padding: '1.15rem 1.2rem',
      border: `1px solid ${colors.border}`,
      fontSize: '0.92rem',
      boxShadow: isDark
        ? '0 22px 48px rgba(0,0,0,0.35)'
        : '0 22px 48px rgba(148,163,184,0.32)',
      alignSelf: 'stretch',
      display: 'flex',
      flexDirection: 'column',
      justifyContent: 'center',
    },
    contactItem: {
      display: 'flex',
      alignItems: 'center',
      gap: '0.45rem',
      marginBottom: '0.42rem',
      color: colors.muted,
      lineHeight: 1.45,
    },
    contactLink: {
      color: isDark ? '#bfdbfe' : '#1d4ed8',
      textDecoration: 'none',
      overflowWrap: 'anywhere',
    },
    contactInlineLink: {
      color: isDark ? '#bfdbfe' : '#1d4ed8',
      textDecoration: 'none',
      fontWeight: 650,
    },
    badge: {
      fontSize: '0.72rem',
      padding: '0.25rem 0.65rem',
      borderRadius: '999px',
      background: colors.okBg,
      border: `1px solid ${colors.okBorder}`,
      color: isDark ? '#a7f3d0' : '#047857',
      lineHeight: 1.4,
    },
    navBar: {
      position: 'sticky',
      top: 0,
      zIndex: 40,
      marginBottom: '2rem',
      padding: '0.65rem 0.7rem',
      backdropFilter: 'blur(16px)',
      background: isDark ? 'rgba(15,23,42,0.9)' : 'rgba(248,250,252,0.94)',
      border: `1px solid ${colors.border}`,
      borderRadius: '1rem',
      transition: 'background 0.25s ease, box-shadow 0.25s ease',
    },
    navBarScrolled: {
      boxShadow: isDark
        ? '0 12px 30px rgba(0,0,0,0.42)'
        : '0 12px 30px rgba(148,163,184,0.42)',
    },
    navBarInner: {
      display: 'flex',
      justifyContent: 'space-between',
      alignItems: 'center',
      gap: '0.75rem',
      flexWrap: 'wrap',
    },
    navBrand: {
      fontSize: '0.78rem',
      textTransform: 'uppercase',
      letterSpacing: '0.16em',
      color: colors.subtle,
      fontWeight: 700,
    },
    navToggleButton: {
      borderRadius: '999px',
      border: `1px solid ${colors.border}`,
      padding: '0.32rem 0.72rem',
      fontSize: '0.95rem',
      background: colors.panelStrong,
      color: colors.text,
      cursor: 'pointer',
    },
    nav: {
      display: 'flex',
      flexWrap: 'wrap',
      gap: '0.55rem',
      fontSize: '0.84rem',
    },
    navMobile: {
      display: 'flex',
      flexDirection: 'column',
      gap: '0.5rem',
      marginTop: '0.75rem',
    },
    navLink: {
      padding: '0.38rem 0.72rem',
      borderRadius: '999px',
      border: '1px solid transparent',
      background: colors.accentSoft,
      color: isDark ? '#dbeafe' : '#1d4ed8',
      cursor: 'pointer',
      transition:
        'background 0.2s ease, color 0.2s ease, border-color 0.2s ease, transform 0.12s ease',
    },
    navLinkSecondary: {
      background: isDark ? 'transparent' : 'rgba(255,255,255,0.72)',
      color: colors.text,
      borderColor: colors.border,
    },
    navLinkActive: {
      borderColor: colors.accentBorder,
      background: colors.accentSoft,
      color: isDark ? '#bfdbfe' : '#1d4ed8',
      transform: 'translateY(-1px)',
      fontWeight: 700,
    },
    section: {
      marginBottom: '2.35rem',
      scrollMarginTop: '112px',
    },
    sectionTitle: {
      fontSize: '1.05rem',
      fontWeight: 750,
      letterSpacing: '0.12em',
      textTransform: 'uppercase',
      color: colors.subtle,
      marginBottom: '0.85rem',
    },
    sectionBody: {
      background: colors.panelBg,
      borderRadius: '1.15rem',
      border: `1px solid ${colors.border}`,
      padding: '1.35rem 1.4rem',
      boxShadow: isDark
        ? '0 16px 36px rgba(0,0,0,0.28)'
        : '0 16px 36px rgba(148,163,184,0.25)',
    },
    paragraph: {
      fontSize: '0.96rem',
      lineHeight: 1.72,
      color: colors.text,
      margin: 0,
    },
    profileGrid: {
      display: 'grid',
      gridTemplateColumns: 'minmax(0, 1fr) minmax(240px, 320px)',
      gap: '1.25rem',
      alignItems: 'start',
    },
    profileLead: {
      fontSize: '1.05rem',
      lineHeight: 1.75,
      color: colors.text,
      margin: '0 0 0.8rem',
      fontWeight: 560,
    },
    quickFacts: {
      display: 'grid',
      gap: '0.65rem',
    },
    quickFact: {
      padding: '0.75rem 0.85rem',
      borderRadius: '0.9rem',
      border: `1px solid ${colors.border}`,
      background: isDark ? 'rgba(2,6,23,0.38)' : 'rgba(248,250,252,0.9)',
    },
    quickFactLabel: {
      display: 'block',
      fontSize: '0.7rem',
      textTransform: 'uppercase',
      letterSpacing: '0.12em',
      color: colors.subtle,
      marginBottom: '0.2rem',
    },
    quickFactValue: {
      display: 'block',
      fontSize: '0.9rem',
      color: colors.text,
      lineHeight: 1.45,
      fontWeight: 600,
    },
    offersColumns: {
      display: 'grid',
      gridTemplateColumns: 'repeat(auto-fit, minmax(260px, 1fr))',
      gap: '1.2rem',
      fontSize: '0.92rem',
    },
    offersTitle: {
      fontSize: '0.92rem',
      fontWeight: 750,
      marginBottom: '0.45rem',
      color: colors.text,
    },
    offersList: {
      paddingLeft: '1.1rem',
      margin: 0,
      lineHeight: 1.65,
      color: colors.text,
    },
    timeline: {
      display: 'flex',
      flexDirection: 'column',
      gap: '1rem',
    },
    timelineItem: {
      position: 'relative',
      display: 'grid',
      gridTemplateColumns: 'auto minmax(0, 1fr)',
      gap: '0.75rem 1.2rem',
      paddingBottom: '1.25rem',
      borderBottom: `1px dashed ${colors.border}`,
    },
    timelineLast: {
      borderBottom: 'none',
      paddingBottom: 0,
    },
    timelineMarkerCol: {
      position: 'relative',
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
      paddingTop: '0.25rem',
    },
    timelineDot: {
      width: '11px',
      height: '11px',
      borderRadius: '999px',
      background: colors.accent,
      border: `2px solid ${isDark ? '#1d4ed8' : '#bfdbfe'}`,
      boxShadow: isDark
        ? '0 0 0 3px rgba(37,99,235,0.35)'
        : '0 0 0 3px rgba(191,219,254,0.9)',
    },
    timelineLine: {
      flex: 1,
      width: '2px',
      marginTop: '0.35rem',
      background: colors.border,
    },
    period: {
      fontSize: '0.78rem',
      textTransform: 'uppercase',
      letterSpacing: '0.08em',
      color: colors.subtle,
      marginBottom: '0.2rem',
      fontWeight: 700,
    },
    role: {
      fontSize: '0.98rem',
      fontWeight: 750,
      color: colors.text,
    },
    org: {
      fontSize: '0.9rem',
      color: colors.muted,
      marginTop: '0.1rem',
    },
    bullets: {
      fontSize: '0.92rem',
      marginTop: '0.45rem',
      marginBottom: 0,
      paddingLeft: '1.05rem',
      color: colors.text,
      lineHeight: 1.62,
    },
    bulletItem: {
      marginBottom: '0.18rem',
    },
    educationItem: {
      display: 'grid',
      gridTemplateColumns: 'auto minmax(0, 1fr)',
      gap: '0.75rem 1.1rem',
      paddingBottom: '1rem',
      borderBottom: `1px dashed ${colors.border}`,
    },
    projectsGrid: {
      display: 'grid',
      gridTemplateColumns: 'repeat(auto-fit, minmax(260px, 1fr))',
      gap: '1rem',
      alignItems: 'stretch',
    },
    projectsGridCompact: {
      display: 'grid',
      gridTemplateColumns: 'repeat(auto-fit, minmax(220px, 1fr))',
      gap: '0.9rem',
      alignItems: 'stretch',
    },
    projectCard: {
      background: colors.panelStrong,
      borderRadius: '1rem',
      border: `1px solid ${colors.border}`,
      padding: '1rem 1.05rem 0.95rem',
      boxShadow: isDark
        ? '0 12px 28px rgba(0,0,0,0.25)'
        : '0 12px 28px rgba(148,163,184,0.22)',
      display: 'flex',
      flexDirection: 'column',
      gap: '0.45rem',
      boxSizing: 'border-box',
    },
    projectTitleRow: {
      display: 'flex',
      flexWrap: 'wrap',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: '0.4rem',
      marginBottom: '0.1rem',
    },
    projectTitle: {
      fontSize: '0.98rem',
      fontWeight: 750,
      wordBreak: 'break-word',
      color: colors.text,
    },
    projectLangTag: {
      fontSize: '0.68rem',
      textTransform: 'uppercase',
      letterSpacing: '0.08em',
      padding: '0.14rem 0.55rem',
      borderRadius: '999px',
      background: colors.accentSoft,
      border: `1px solid ${colors.accentBorder}`,
      color: isDark ? '#dbeafe' : '#1d4ed8',
      whiteSpace: 'nowrap',
      fontWeight: 700,
    },
    projectDescription: {
      fontSize: '0.88rem',
      lineHeight: 1.58,
      color: colors.muted,
      margin: 0,
    },
    projectTags: {
      display: 'flex',
      flexWrap: 'wrap',
      gap: '0.32rem',
      marginTop: '0.15rem',
    },
    projectMiniTag: {
      fontSize: '0.72rem',
      borderRadius: '999px',
      padding: '0.12rem 0.5rem',
      border: `1px solid ${colors.border}`,
      color: colors.muted,
      background: isDark ? 'rgba(2,6,23,0.26)' : 'rgba(248,250,252,0.86)',
    },
    projectLink: {
      marginTop: 'auto',
      fontSize: '0.82rem',
      textDecoration: 'none',
      alignSelf: 'flex-start',
      borderRadius: '999px',
      padding: '0.25rem 0.62rem',
      border: `1px solid ${colors.accentBorder}`,
      background: colors.accentSoft,
      color: isDark ? '#93c5fd' : '#2563eb',
      display: 'inline-flex',
      alignItems: 'center',
      gap: '0.25rem',
      fontWeight: 650,
    },
    latestProjectsBlock: {
      marginTop: '1.35rem',
    },
    projectsSubTitle: {
      fontSize: '0.82rem',
      textTransform: 'uppercase',
      letterSpacing: '0.12em',
      color: colors.subtle,
      margin: '0 0 0.75rem',
    },
    skillColumns: {
      display: 'grid',
      gridTemplateColumns: 'repeat(auto-fit, minmax(220px, 1fr))',
      gap: '1rem',
      fontSize: '0.9rem',
    },
    skillGroupTitle: {
      fontSize: '0.78rem',
      textTransform: 'uppercase',
      letterSpacing: '0.12em',
      color: colors.subtle,
      marginBottom: '0.5rem',
      fontWeight: 750,
    },
    skillList: {
      listStyle: 'none',
      padding: 0,
      margin: 0,
      display: 'grid',
      gap: '0.4rem',
    },
    skillItem: {
      lineHeight: 1.5,
      color: colors.text,
    },
    pillRow: {
      display: 'flex',
      flexWrap: 'wrap',
      gap: '0.4rem',
      marginTop: '0.4rem',
    },
    pill: {
      fontSize: '0.78rem',
      padding: '0.18rem 0.6rem',
      borderRadius: '999px',
      background: colors.accentSoft,
      border: `1px solid ${colors.accentBorder}`,
      color: isDark ? '#dbeafe' : '#1d4ed8',
      fontWeight: 600,
    },
    contactLayout: {
      display: 'grid',
      gridTemplateColumns: 'repeat(auto-fit, minmax(260px, 1fr))',
      gap: '1.2rem',
      alignItems: 'flex-start',
    },
    contactText: {
      fontSize: '0.94rem',
      lineHeight: 1.68,
      color: colors.text,
    },
    contactForm: {
      display: 'flex',
      flexDirection: 'column',
      gap: '0.72rem',
    },
    formLabel: {
      fontSize: '0.76rem',
      textTransform: 'uppercase',
      letterSpacing: '0.12em',
      color: colors.subtle,
      marginBottom: '0.25rem',
      display: 'block',
      fontWeight: 700,
    },
    formInput: {
      width: '100%',
      borderRadius: '0.7rem',
      border: `1px solid ${colors.border}`,
      padding: '0.55rem 0.68rem',
      fontSize: '0.92rem',
      background: isDark ? 'rgba(15,23,42,0.95)' : '#ffffff',
      color: colors.text,
      outline: 'none',
      boxSizing: 'border-box',
    },
    formTextarea: {
      width: '100%',
      borderRadius: '0.7rem',
      border: `1px solid ${colors.border}`,
      padding: '0.6rem 0.68rem',
      fontSize: '0.92rem',
      minHeight: '120px',
      resize: 'vertical',
      background: isDark ? 'rgba(15,23,42,0.95)' : '#ffffff',
      color: colors.text,
      outline: 'none',
      boxSizing: 'border-box',
    },
    formButton: {
      alignSelf: 'flex-start',
      borderRadius: '999px',
      border: `1px solid ${colors.accentBorder}`,
      padding: '0.45rem 0.95rem',
      fontSize: '0.86rem',
      background: colors.accentSoft,
      color: isDark ? '#bfdbfe' : '#1d4ed8',
      cursor: 'pointer',
      display: 'inline-flex',
      alignItems: 'center',
      gap: '0.3rem',
      fontWeight: 700,
    },
    formFeedbackOk: {
      fontSize: '0.84rem',
      marginTop: '0.1rem',
      color: isDark ? '#6ee7b7' : '#047857',
      lineHeight: 1.5,
    },
    formFeedbackError: {
      fontSize: '0.84rem',
      marginTop: '0.1rem',
      color: isDark ? '#fecaca' : '#b91c1c',
      lineHeight: 1.5,
    },
    footer: {
      marginTop: '1.5rem',
      fontSize: '0.78rem',
      color: colors.subtle,
      textAlign: 'center',
      display: 'grid',
      gap: '0.25rem',
    },
    toTopButton: {
      position: 'fixed',
      right: '1.5rem',
      bottom: '1.5rem',
      zIndex: 50,
      borderRadius: '999px',
      border: `1px solid ${colors.border}`,
      padding: '0.48rem 0.72rem',
      fontSize: '0.9rem',
      background: colors.panelStrong,
      color: colors.text,
      boxShadow: isDark
        ? '0 10px 30px rgba(0,0,0,0.42)'
        : '0 10px 30px rgba(148,163,184,0.45)',
      cursor: 'pointer',
    },
  }
}
